/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.chamados.view;

import br.com.chamados.genericos.AcoesPainel;

/**
 *
 * @author lksbr
 */
public class JpDefault extends javax.swing.JPanel {

    private AcoesPainel acoesPainel;

    /**
     * Creates new form JpDefault
     */
    public JpDefault(AcoesPainel acoesPainel) {
        this();
        this.acoesPainel = acoesPainel;
    }

    public JpDefault() {
        initComponents();
        jbInserir.setEnabled(false);
        jbAlterar.setEnabled(false);
        jbDeletar.setEnabled(false);

    }

    public AcoesPainel getAcoesPainel() {
        return acoesPainel;
    }

    public void setAcoesCadastro(AcoesPainel acoesPainel) {
        this.acoesPainel = acoesPainel;
        acoesPainel.checkEnabled(jbInserir, jbAlterar, jbDeletar);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbPesquisar = new javax.swing.JButton();
        jbVaPara = new javax.swing.JButton();
        jbInserir = new javax.swing.JButton();
        jbAlterar = new javax.swing.JButton();
        jbDeletar = new javax.swing.JButton();

        jbPesquisar.setText("Pesquisar");
        jbPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPesquisarActionPerformed(evt);
            }
        });

        jbVaPara.setText("Vá para");
        jbVaPara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVaParaActionPerformed(evt);
            }
        });

        jbInserir.setText("Inserir");
        jbInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbInserirActionPerformed(evt);
            }
        });

        jbAlterar.setText("Alterar");
        jbAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAlterarActionPerformed(evt);
            }
        });

        jbDeletar.setText("Deletar");
        jbDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDeletarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbVaPara)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbPesquisar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbInserir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbAlterar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbDeletar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jbDeletar)
                    .addComponent(jbAlterar)
                    .addComponent(jbInserir)
                    .addComponent(jbPesquisar)
                    .addComponent(jbVaPara))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPesquisarActionPerformed
        if (acoesPainel != null) {
            acoesPainel.pesquisar();
        }
    }//GEN-LAST:event_jbPesquisarActionPerformed

    private void jbVaParaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVaParaActionPerformed
        if (acoesPainel != null) {
            acoesPainel.vaPara("");
        }
    }//GEN-LAST:event_jbVaParaActionPerformed

    private void jbInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbInserirActionPerformed
        if (acoesPainel != null) {
            acoesPainel.inserir();
        }
    }//GEN-LAST:event_jbInserirActionPerformed

    private void jbAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAlterarActionPerformed
        if (acoesPainel != null) {
            acoesPainel.alterar();
        }
    }//GEN-LAST:event_jbAlterarActionPerformed

    private void jbDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDeletarActionPerformed
        if (acoesPainel != null) {
            acoesPainel.deletar();
        }
    }//GEN-LAST:event_jbDeletarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbAlterar;
    private javax.swing.JButton jbDeletar;
    private javax.swing.JButton jbInserir;
    private javax.swing.JButton jbPesquisar;
    private javax.swing.JButton jbVaPara;
    // End of variables declaration//GEN-END:variables
}
