package br.com.chamados.model;
// Generated 30/08/2015 21:21:25 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Acompanhamento generated by hbm2java
 */
@Entity
@Table(name="acompanhamento"
    ,catalog="chamados"
)
public class Acompanhamento  implements java.io.Serializable {


     private int id;
     private String descricao;
     private Set interacaos = new HashSet(0);

    public Acompanhamento() {
    }

	
    public Acompanhamento(int id) {
        this.id = id;
    }
    public Acompanhamento(int id, String descricao, Set interacaos) {
       this.id = id;
       this.descricao = descricao;
       this.interacaos = interacaos;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="descricao", length=100)
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="acompanhamento")
    public Set getInteracaos() {
        return this.interacaos;
    }
    
    public void setInteracaos(Set interacaos) {
        this.interacaos = interacaos;
    }




}


