package br.com.chamados.model;
// Generated 14/12/2015 00:31:21 by Hibernate Tools 4.3.1



/**
 * Acompanhamento generated by hbm2java
 */
public class Acompanhamento  implements java.io.Serializable {


     private int id;
     private String descricao;

    public Acompanhamento() {
    }

	
    public Acompanhamento(int id) {
        this.id = id;
    }
    public Acompanhamento(int id, String descricao) {
       this.id = id;
       this.descricao = descricao;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }




}


