package br.com.chamados.model;
// Generated 01/11/2015 20:44:12 by Hibernate Tools 4.3.1



/**
 * AudTrigger generated by hbm2java
 */
public class AudTrigger  implements java.io.Serializable {


     private Integer id;
     private String nome;
     private Boolean situacao;

    public AudTrigger() {
    }

    public AudTrigger(String nome, Boolean situacao) {
       this.nome = nome;
       this.situacao = situacao;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Boolean getSituacao() {
        return this.situacao;
    }
    
    public void setSituacao(Boolean situacao) {
        this.situacao = situacao;
    }




}


