package br.com.chamados.model;
// Generated 30/08/2015 21:21:25 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Bairro generated by hbm2java
 */
@Entity
@Table(name="bairro"
    ,catalog="chamados"
)
public class Bairro  implements java.io.Serializable {


     private int id;
     private Cidade cidade;
     private String descricao;
     private Set pessoas = new HashSet(0);
     private Set funcionarios = new HashSet(0);
     private Set clientes = new HashSet(0);

    public Bairro() {
    }

	
    public Bairro(int id, Cidade cidade, String descricao) {
        this.id = id;
        this.cidade = cidade;
        this.descricao = descricao;
    }
    public Bairro(int id, Cidade cidade, String descricao, Set pessoas, Set funcionarios, Set clientes) {
       this.id = id;
       this.cidade = cidade;
       this.descricao = descricao;
       this.pessoas = pessoas;
       this.funcionarios = funcionarios;
       this.clientes = clientes;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cidade_id", nullable=false)
    public Cidade getCidade() {
        return this.cidade;
    }
    
    public void setCidade(Cidade cidade) {
        this.cidade = cidade;
    }

    
    @Column(name="descricao", nullable=false, length=45)
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="bairro")
    public Set getPessoas() {
        return this.pessoas;
    }
    
    public void setPessoas(Set pessoas) {
        this.pessoas = pessoas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="bairro")
    public Set getFuncionarios() {
        return this.funcionarios;
    }
    
    public void setFuncionarios(Set funcionarios) {
        this.funcionarios = funcionarios;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="bairro")
    public Set getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Set clientes) {
        this.clientes = clientes;
    }




}


