package br.com.chamados.model;
// Generated 21/09/2015 21:01:59 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Bairro generated by hbm2java
 */
public class Bairro  implements java.io.Serializable {


     private int id;
     private Cidade cidade;
     private String descricao;
     private Set empresas = new HashSet(0);
     private Set funcionarios = new HashSet(0);
     private Set pessoas = new HashSet(0);

    public Bairro() {
    }

	
    public Bairro(int id, Cidade cidade, String descricao) {
        this.id = id;
        this.cidade = cidade;
        this.descricao = descricao;
    }
    public Bairro(int id, Cidade cidade, String descricao, Set empresas, Set funcionarios, Set pessoas) {
       this.id = id;
       this.cidade = cidade;
       this.descricao = descricao;
       this.empresas = empresas;
       this.funcionarios = funcionarios;
       this.pessoas = pessoas;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Cidade getCidade() {
        return this.cidade;
    }
    
    public void setCidade(Cidade cidade) {
        this.cidade = cidade;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public Set getEmpresas() {
        return this.empresas;
    }
    
    public void setEmpresas(Set empresas) {
        this.empresas = empresas;
    }
    public Set getFuncionarios() {
        return this.funcionarios;
    }
    
    public void setFuncionarios(Set funcionarios) {
        this.funcionarios = funcionarios;
    }
    public Set getPessoas() {
        return this.pessoas;
    }
    
    public void setPessoas(Set pessoas) {
        this.pessoas = pessoas;
    }




}


