package br.com.chamados.model;
// Generated 26/10/2015 20:18:40 by Hibernate Tools 4.3.1



/**
 * CategoriaTres generated by hbm2java
 */
public class CategoriaTres  implements java.io.Serializable {


     private Integer id;
     private CategoriaDois categoriaDois;
     private String descricao;

    public CategoriaTres() {
    }

	
    public CategoriaTres(CategoriaDois categoriaDois) {
        this.categoriaDois = categoriaDois;
    }
    public CategoriaTres(CategoriaDois categoriaDois, String descricao) {
       this.categoriaDois = categoriaDois;
       this.descricao = descricao;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public CategoriaDois getCategoriaDois() {
        return this.categoriaDois;
    }
    
    public void setCategoriaDois(CategoriaDois categoriaDois) {
        this.categoriaDois = categoriaDois;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }




}


