package br.com.chamados.model;
// Generated 30/08/2015 21:21:25 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CategoriaUm generated by hbm2java
 */
@Entity
@Table(name="categoria_um"
    ,catalog="chamados"
)
public class CategoriaUm  implements java.io.Serializable {


     private Integer id;
     private String descricao;
     private Set chamados = new HashSet(0);
     private Set categoriaDoises = new HashSet(0);

    public CategoriaUm() {
    }

    public CategoriaUm(String descricao, Set chamados, Set categoriaDoises) {
       this.descricao = descricao;
       this.chamados = chamados;
       this.categoriaDoises = categoriaDoises;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="descricao", length=45)
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="categoriaUm")
    public Set getChamados() {
        return this.chamados;
    }
    
    public void setChamados(Set chamados) {
        this.chamados = chamados;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="categoriaUm")
    public Set getCategoriaDoises() {
        return this.categoriaDoises;
    }
    
    public void setCategoriaDoises(Set categoriaDoises) {
        this.categoriaDoises = categoriaDoises;
    }




}


