package br.com.chamados.model;
// Generated 26/10/2015 20:54:38 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Chamado generated by hbm2java
 */
public class Chamado  implements java.io.Serializable {


     private Integer id;
     private CategoriaUm categoriaUm;
     private Chamado chamado;
     private Empresa empresa;
     private Funcionario funcionario;
     private Origem origem;
     private Pessoa pessoa;
     private Prioridade prioridade;
     private Situacao situacao;
     private Tipo tipo;
     private int idAbertura;
     private String titulo;
     private String descricao;
     private Date dataAbertura;
     private Date dataFechamento;
     private Date dataPrevista;
     private Set chamados = new HashSet(0);
     private Set interacaos = new HashSet(0);

    public Chamado() {
    }

	
    public Chamado(CategoriaUm categoriaUm, Origem origem, Prioridade prioridade, Situacao situacao, Tipo tipo, int idAbertura, String titulo) {
        this.categoriaUm = categoriaUm;
        this.origem = origem;
        this.prioridade = prioridade;
        this.situacao = situacao;
        this.tipo = tipo;
        this.idAbertura = idAbertura;
        this.titulo = titulo;
    }
    public Chamado(CategoriaUm categoriaUm, Chamado chamado, Empresa empresa, Funcionario funcionario, Origem origem, Pessoa pessoa, Prioridade prioridade, Situacao situacao, Tipo tipo, int idAbertura, String titulo, String descricao, Date dataAbertura, Date dataFechamento, Date dataPrevista, Set chamados, Set interacaos) {
       this.categoriaUm = categoriaUm;
       this.chamado = chamado;
       this.empresa = empresa;
       this.funcionario = funcionario;
       this.origem = origem;
       this.pessoa = pessoa;
       this.prioridade = prioridade;
       this.situacao = situacao;
       this.tipo = tipo;
       this.idAbertura = idAbertura;
       this.titulo = titulo;
       this.descricao = descricao;
       this.dataAbertura = dataAbertura;
       this.dataFechamento = dataFechamento;
       this.dataPrevista = dataPrevista;
       this.chamados = chamados;
       this.interacaos = interacaos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public CategoriaUm getCategoriaUm() {
        return this.categoriaUm;
    }
    
    public void setCategoriaUm(CategoriaUm categoriaUm) {
        this.categoriaUm = categoriaUm;
    }
    public Chamado getChamado() {
        return this.chamado;
    }
    
    public void setChamado(Chamado chamado) {
        this.chamado = chamado;
    }
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }
    public Funcionario getFuncionario() {
        return this.funcionario;
    }
    
    public void setFuncionario(Funcionario funcionario) {
        this.funcionario = funcionario;
    }
    public Origem getOrigem() {
        return this.origem;
    }
    
    public void setOrigem(Origem origem) {
        this.origem = origem;
    }
    public Pessoa getPessoa() {
        return this.pessoa;
    }
    
    public void setPessoa(Pessoa pessoa) {
        this.pessoa = pessoa;
    }
    public Prioridade getPrioridade() {
        return this.prioridade;
    }
    
    public void setPrioridade(Prioridade prioridade) {
        this.prioridade = prioridade;
    }
    public Situacao getSituacao() {
        return this.situacao;
    }
    
    public void setSituacao(Situacao situacao) {
        this.situacao = situacao;
    }
    public Tipo getTipo() {
        return this.tipo;
    }
    
    public void setTipo(Tipo tipo) {
        this.tipo = tipo;
    }
    public int getIdAbertura() {
        return this.idAbertura;
    }
    
    public void setIdAbertura(int idAbertura) {
        this.idAbertura = idAbertura;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public Date getDataAbertura() {
        return this.dataAbertura;
    }
    
    public void setDataAbertura(Date dataAbertura) {
        this.dataAbertura = dataAbertura;
    }
    public Date getDataFechamento() {
        return this.dataFechamento;
    }
    
    public void setDataFechamento(Date dataFechamento) {
        this.dataFechamento = dataFechamento;
    }
    public Date getDataPrevista() {
        return this.dataPrevista;
    }
    
    public void setDataPrevista(Date dataPrevista) {
        this.dataPrevista = dataPrevista;
    }
    public Set getChamados() {
        return this.chamados;
    }
    
    public void setChamados(Set chamados) {
        this.chamados = chamados;
    }
    public Set getInteracaos() {
        return this.interacaos;
    }
    
    public void setInteracaos(Set interacaos) {
        this.interacaos = interacaos;
    }




}


