package br.com.chamados.model;
// Generated 24/08/2015 20:26:41 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Cidade generated by hbm2java
 */
@Entity
@Table(name="cidade"
    ,catalog="chamados"
)
public class Cidade  implements java.io.Serializable {


     private int id;
     private Estado estado;
     private String nome;
     private String cep;
     private Set bairros = new HashSet(0);
     private Set clientes = new HashSet(0);

    public Cidade() {
    }

	
    public Cidade(int id, Estado estado, String nome, String cep) {
        this.id = id;
        this.estado = estado;
        this.nome = nome;
        this.cep = cep;
    }
    public Cidade(int id, Estado estado, String nome, String cep, Set bairros, Set clientes) {
       this.id = id;
       this.estado = estado;
       this.nome = nome;
       this.cep = cep;
       this.bairros = bairros;
       this.clientes = clientes;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="estado_id", nullable=false)
    public Estado getEstado() {
        return this.estado;
    }
    
    public void setEstado(Estado estado) {
        this.estado = estado;
    }

    
    @Column(name="nome", nullable=false, length=45)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="cep", nullable=false, length=45)
    public String getCep() {
        return this.cep;
    }
    
    public void setCep(String cep) {
        this.cep = cep;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cidade")
    public Set getBairros() {
        return this.bairros;
    }
    
    public void setBairros(Set bairros) {
        this.bairros = bairros;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cidade")
    public Set getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Set clientes) {
        this.clientes = clientes;
    }




}


