package br.com.chamados.model;
// Generated 01/11/2015 20:44:12 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cidade generated by hbm2java
 */
public class Cidade  implements java.io.Serializable {


     private Integer id;
     private Estado estado;
     private String nome;
     private String cep;
     private Set empresas = new HashSet(0);
     private Set pessoas = new HashSet(0);

    public Cidade() {
    }

	
    public Cidade(Estado estado, String nome, String cep) {
        this.estado = estado;
        this.nome = nome;
        this.cep = cep;
    }
    public Cidade(Estado estado, String nome, String cep, Set empresas, Set pessoas) {
       this.estado = estado;
       this.nome = nome;
       this.cep = cep;
       this.empresas = empresas;
       this.pessoas = pessoas;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Estado getEstado() {
        return this.estado;
    }
    
    public void setEstado(Estado estado) {
        this.estado = estado;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getCep() {
        return this.cep;
    }
    
    public void setCep(String cep) {
        this.cep = cep;
    }
    public Set getEmpresas() {
        return this.empresas;
    }
    
    public void setEmpresas(Set empresas) {
        this.empresas = empresas;
    }
    public Set getPessoas() {
        return this.pessoas;
    }
    
    public void setPessoas(Set pessoas) {
        this.pessoas = pessoas;
    }




}


