package br.com.chamados.model;
// Generated 21/09/2015 21:01:59 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Funcionario generated by hbm2java
 */
public class Funcionario  implements java.io.Serializable {


     private int pessoaId;
     private Bairro bairro;
     private Cidade cidade;
     private Empresa empresa;
     private Funcao funcao;
     private Pessoa pessoa;
     private Setor setor;
     private Usuario usuario;
     private Date dataAdmicao;
     private Date dataDesligamento;
     private int id;
     private Set chamadosForFuncionarioAberturaId = new HashSet(0);
     private Set chamadosForFuncionarioAtendenteId = new HashSet(0);
     private Set chamadosForFuncionarioSolicitanteId = new HashSet(0);

    public Funcionario() {
    }

	
    public Funcionario(Bairro bairro, Cidade cidade, Empresa empresa, Funcao funcao, Pessoa pessoa, Setor setor, Usuario usuario, Date dataAdmicao, int id) {
        this.bairro = bairro;
        this.cidade = cidade;
        this.empresa = empresa;
        this.funcao = funcao;
        this.pessoa = pessoa;
        this.setor = setor;
        this.usuario = usuario;
        this.dataAdmicao = dataAdmicao;
        this.id = id;
    }
    public Funcionario(Bairro bairro, Cidade cidade, Empresa empresa, Funcao funcao, Pessoa pessoa, Setor setor, Usuario usuario, Date dataAdmicao, Date dataDesligamento, int id, Set chamadosForFuncionarioAberturaId, Set chamadosForFuncionarioAtendenteId, Set chamadosForFuncionarioSolicitanteId) {
       this.bairro = bairro;
       this.cidade = cidade;
       this.empresa = empresa;
       this.funcao = funcao;
       this.pessoa = pessoa;
       this.setor = setor;
       this.usuario = usuario;
       this.dataAdmicao = dataAdmicao;
       this.dataDesligamento = dataDesligamento;
       this.id = id;
       this.chamadosForFuncionarioAberturaId = chamadosForFuncionarioAberturaId;
       this.chamadosForFuncionarioAtendenteId = chamadosForFuncionarioAtendenteId;
       this.chamadosForFuncionarioSolicitanteId = chamadosForFuncionarioSolicitanteId;
    }
   
    public int getPessoaId() {
        return this.pessoaId;
    }
    
    public void setPessoaId(int pessoaId) {
        this.pessoaId = pessoaId;
    }
    public Bairro getBairro() {
        return this.bairro;
    }
    
    public void setBairro(Bairro bairro) {
        this.bairro = bairro;
    }
    public Cidade getCidade() {
        return this.cidade;
    }
    
    public void setCidade(Cidade cidade) {
        this.cidade = cidade;
    }
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }
    public Funcao getFuncao() {
        return this.funcao;
    }
    
    public void setFuncao(Funcao funcao) {
        this.funcao = funcao;
    }
    public Pessoa getPessoa() {
        return this.pessoa;
    }
    
    public void setPessoa(Pessoa pessoa) {
        this.pessoa = pessoa;
    }
    public Setor getSetor() {
        return this.setor;
    }
    
    public void setSetor(Setor setor) {
        this.setor = setor;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Date getDataAdmicao() {
        return this.dataAdmicao;
    }
    
    public void setDataAdmicao(Date dataAdmicao) {
        this.dataAdmicao = dataAdmicao;
    }
    public Date getDataDesligamento() {
        return this.dataDesligamento;
    }
    
    public void setDataDesligamento(Date dataDesligamento) {
        this.dataDesligamento = dataDesligamento;
    }
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Set getChamadosForFuncionarioAberturaId() {
        return this.chamadosForFuncionarioAberturaId;
    }
    
    public void setChamadosForFuncionarioAberturaId(Set chamadosForFuncionarioAberturaId) {
        this.chamadosForFuncionarioAberturaId = chamadosForFuncionarioAberturaId;
    }
    public Set getChamadosForFuncionarioAtendenteId() {
        return this.chamadosForFuncionarioAtendenteId;
    }
    
    public void setChamadosForFuncionarioAtendenteId(Set chamadosForFuncionarioAtendenteId) {
        this.chamadosForFuncionarioAtendenteId = chamadosForFuncionarioAtendenteId;
    }
    public Set getChamadosForFuncionarioSolicitanteId() {
        return this.chamadosForFuncionarioSolicitanteId;
    }
    
    public void setChamadosForFuncionarioSolicitanteId(Set chamadosForFuncionarioSolicitanteId) {
        this.chamadosForFuncionarioSolicitanteId = chamadosForFuncionarioSolicitanteId;
    }




}


