package br.com.chamados.model;
// Generated 30/08/2015 21:21:25 by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * FuncionarioHasTela generated by hbm2java
 */
@Entity
@Table(name="funcionario_has_tela"
    ,catalog="chamados"
)
public class FuncionarioHasTela  implements java.io.Serializable {


     private FuncionarioHasTelaId id;
     private Funcionario funcionario;
     private Tela tela;
     private boolean consultar;
     private boolean inserir;
     private boolean alterar;
     private boolean deletar;

    public FuncionarioHasTela() {
    }

    public FuncionarioHasTela(FuncionarioHasTelaId id, Funcionario funcionario, Tela tela, boolean consultar, boolean inserir, boolean alterar, boolean deletar) {
       this.id = id;
       this.funcionario = funcionario;
       this.tela = tela;
       this.consultar = consultar;
       this.inserir = inserir;
       this.alterar = alterar;
       this.deletar = deletar;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="funcionarioId", column=@Column(name="funcionario_id", nullable=false) ), 
        @AttributeOverride(name="telaId", column=@Column(name="tela_id", nullable=false) ) } )
    public FuncionarioHasTelaId getId() {
        return this.id;
    }
    
    public void setId(FuncionarioHasTelaId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="funcionario_id", nullable=false, insertable=false, updatable=false)
    public Funcionario getFuncionario() {
        return this.funcionario;
    }
    
    public void setFuncionario(Funcionario funcionario) {
        this.funcionario = funcionario;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="tela_id", nullable=false, insertable=false, updatable=false)
    public Tela getTela() {
        return this.tela;
    }
    
    public void setTela(Tela tela) {
        this.tela = tela;
    }

    
    @Column(name="consultar", nullable=false)
    public boolean isConsultar() {
        return this.consultar;
    }
    
    public void setConsultar(boolean consultar) {
        this.consultar = consultar;
    }

    
    @Column(name="inserir", nullable=false)
    public boolean isInserir() {
        return this.inserir;
    }
    
    public void setInserir(boolean inserir) {
        this.inserir = inserir;
    }

    
    @Column(name="alterar", nullable=false)
    public boolean isAlterar() {
        return this.alterar;
    }
    
    public void setAlterar(boolean alterar) {
        this.alterar = alterar;
    }

    
    @Column(name="deletar", nullable=false)
    public boolean isDeletar() {
        return this.deletar;
    }
    
    public void setDeletar(boolean deletar) {
        this.deletar = deletar;
    }




}


