package br.com.chamados.model;
// Generated 26/10/2015 20:54:38 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Interacao generated by hbm2java
 */
public class Interacao  implements java.io.Serializable {


     private Integer id;
     private Acompanhamento acompanhamento;
     private Chamado chamado;
     private String descricao;
     private Date data;
     private Integer autorId;
     private Character tipoAutor;
     private Boolean solucao;
     private Boolean privado;
     private Boolean email;

    public Interacao() {
    }

	
    public Interacao(Acompanhamento acompanhamento, Chamado chamado, String descricao, Date data) {
        this.acompanhamento = acompanhamento;
        this.chamado = chamado;
        this.descricao = descricao;
        this.data = data;
    }
    public Interacao(Acompanhamento acompanhamento, Chamado chamado, String descricao, Date data, Integer autorId, Character tipoAutor, Boolean solucao, Boolean privado, Boolean email) {
       this.acompanhamento = acompanhamento;
       this.chamado = chamado;
       this.descricao = descricao;
       this.data = data;
       this.autorId = autorId;
       this.tipoAutor = tipoAutor;
       this.solucao = solucao;
       this.privado = privado;
       this.email = email;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Acompanhamento getAcompanhamento() {
        return this.acompanhamento;
    }
    
    public void setAcompanhamento(Acompanhamento acompanhamento) {
        this.acompanhamento = acompanhamento;
    }
    public Chamado getChamado() {
        return this.chamado;
    }
    
    public void setChamado(Chamado chamado) {
        this.chamado = chamado;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }
    public Integer getAutorId() {
        return this.autorId;
    }
    
    public void setAutorId(Integer autorId) {
        this.autorId = autorId;
    }
    public Character getTipoAutor() {
        return this.tipoAutor;
    }
    
    public void setTipoAutor(Character tipoAutor) {
        this.tipoAutor = tipoAutor;
    }
    public Boolean getSolucao() {
        return this.solucao;
    }
    
    public void setSolucao(Boolean solucao) {
        this.solucao = solucao;
    }
    public Boolean getPrivado() {
        return this.privado;
    }
    
    public void setPrivado(Boolean privado) {
        this.privado = privado;
    }
    public Boolean getEmail() {
        return this.email;
    }
    
    public void setEmail(Boolean email) {
        this.email = email;
    }




}


