package br.com.chamados.model;
// Generated 24/08/2015 20:26:41 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * InteracaoId generated by hbm2java
 */
@Embeddable
public class InteracaoId  implements java.io.Serializable {


     private int id;
     private int chamadoId;

    public InteracaoId() {
    }

    public InteracaoId(int id, int chamadoId) {
       this.id = id;
       this.chamadoId = chamadoId;
    }
   


    @Column(name="id", nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }


    @Column(name="chamado_id", nullable=false)
    public int getChamadoId() {
        return this.chamadoId;
    }
    
    public void setChamadoId(int chamadoId) {
        this.chamadoId = chamadoId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof InteracaoId) ) return false;
		 InteracaoId castOther = ( InteracaoId ) other; 
         
		 return (this.getId()==castOther.getId())
 && (this.getChamadoId()==castOther.getChamadoId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getId();
         result = 37 * result + this.getChamadoId();
         return result;
   }   


}


