package br.com.chamados.model;
// Generated 06/09/2015 10:21:06 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Nivel generated by hbm2java
 */
public class Nivel  implements java.io.Serializable {


     private int id;
     private String descricao;
     private Set funcaos = new HashSet(0);

    public Nivel() {
    }

	
    public Nivel(int id) {
        this.id = id;
    }
    public Nivel(int id, String descricao, Set funcaos) {
       this.id = id;
       this.descricao = descricao;
       this.funcaos = funcaos;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public Set getFuncaos() {
        return this.funcaos;
    }
    
    public void setFuncaos(Set funcaos) {
        this.funcaos = funcaos;
    }




}


