package br.com.chamados.model;
// Generated 29/11/2015 11:17:34 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Origem generated by hbm2java
 */
public class Origem  implements java.io.Serializable {


     private int id;
     private String descricao;
     private Set chamados = new HashSet(0);

    public Origem() {
    }

	
    public Origem(int id, String descricao) {
        this.id = id;
        this.descricao = descricao;
    }
    public Origem(int id, String descricao, Set chamados) {
       this.id = id;
       this.descricao = descricao;
       this.chamados = chamados;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public Set getChamados() {
        return this.chamados;
    }
    
    public void setChamados(Set chamados) {
        this.chamados = chamados;
    }
    public String getNome() {
        return getDescricao();
    }





}


