package br.com.chamados.model;
// Generated 21/09/2015 21:01:59 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Pessoa generated by hbm2java
 */
public class Pessoa  implements java.io.Serializable {


     private Integer id;
     private Bairro bairro;
     private Cidade cidade;
     private Empresa empresa;
     private String nome;
     private int idade;
     private Date dataNascimento;
     private String email;
     private String telefone;
     private String cpf;
     private String rg;
     private Set chamados = new HashSet(0);
     private Funcionario funcionario;

    public Pessoa() {
    }

	
    public Pessoa(Bairro bairro, Cidade cidade, Empresa empresa, String nome, int idade, Date dataNascimento, String email, String telefone, String cpf, String rg) {
        this.bairro = bairro;
        this.cidade = cidade;
        this.empresa = empresa;
        this.nome = nome;
        this.idade = idade;
        this.dataNascimento = dataNascimento;
        this.email = email;
        this.telefone = telefone;
        this.cpf = cpf;
        this.rg = rg;
    }
    public Pessoa(Bairro bairro, Cidade cidade, Empresa empresa, String nome, int idade, Date dataNascimento, String email, String telefone, String cpf, String rg, Set chamados, Funcionario funcionario) {
       this.bairro = bairro;
       this.cidade = cidade;
       this.empresa = empresa;
       this.nome = nome;
       this.idade = idade;
       this.dataNascimento = dataNascimento;
       this.email = email;
       this.telefone = telefone;
       this.cpf = cpf;
       this.rg = rg;
       this.chamados = chamados;
       this.funcionario = funcionario;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Bairro getBairro() {
        return this.bairro;
    }
    
    public void setBairro(Bairro bairro) {
        this.bairro = bairro;
    }
    public Cidade getCidade() {
        return this.cidade;
    }
    
    public void setCidade(Cidade cidade) {
        this.cidade = cidade;
    }
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public int getIdade() {
        return this.idade;
    }
    
    public void setIdade(int idade) {
        this.idade = idade;
    }
    public Date getDataNascimento() {
        return this.dataNascimento;
    }
    
    public void setDataNascimento(Date dataNascimento) {
        this.dataNascimento = dataNascimento;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }
    public String getCpf() {
        return this.cpf;
    }
    
    public void setCpf(String cpf) {
        this.cpf = cpf;
    }
    public String getRg() {
        return this.rg;
    }
    
    public void setRg(String rg) {
        this.rg = rg;
    }
    public Set getChamados() {
        return this.chamados;
    }
    
    public void setChamados(Set chamados) {
        this.chamados = chamados;
    }
    public Funcionario getFuncionario() {
        return this.funcionario;
    }
    
    public void setFuncionario(Funcionario funcionario) {
        this.funcionario = funcionario;
    }




}


