package br.com.chamados.model;
// Generated 26/10/2015 20:18:40 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer id;
     private Funcionario funcionario;
     private String login;
     private String senha;
     private Set permissoeses = new HashSet(0);
     private Set auditorias = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(Funcionario funcionario, String login, String senha) {
        this.funcionario = funcionario;
        this.login = login;
        this.senha = senha;
    }
    public Usuario(Funcionario funcionario, String login, String senha, Set permissoeses, Set auditorias) {
       this.funcionario = funcionario;
       this.login = login;
       this.senha = senha;
       this.permissoeses = permissoeses;
       this.auditorias = auditorias;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Funcionario getFuncionario() {
        return this.funcionario;
    }
    
    public void setFuncionario(Funcionario funcionario) {
        this.funcionario = funcionario;
    }
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }
    public Set getPermissoeses() {
        return this.permissoeses;
    }
    
    public void setPermissoeses(Set permissoeses) {
        this.permissoeses = permissoeses;
    }
    public Set getAuditorias() {
        return this.auditorias;
    }
    
    public void setAuditorias(Set auditorias) {
        this.auditorias = auditorias;
    }




}


