package br.com.chamados.model;
// Generated 20/09/2015 15:42:06 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer id;
     private String login;
     private String senha;
     private Set funcionarios = new HashSet(0);
     private Set permicoeses = new HashSet(0);
     private Set permissoeses = new HashSet(0);
     private Set auditorias = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(String login, String senha) {
        this.login = login;
        this.senha = senha;
    }
    public Usuario(String login, String senha, Set funcionarios, Set permicoeses, Set permissoeses, Set auditorias) {
       this.login = login;
       this.senha = senha;
       this.funcionarios = funcionarios;
       this.permicoeses = permicoeses;
       this.permissoeses = permissoeses;
       this.auditorias = auditorias;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }
    public Set getFuncionarios() {
        return this.funcionarios;
    }
    
    public void setFuncionarios(Set funcionarios) {
        this.funcionarios = funcionarios;
    }
    public Set getPermicoeses() {
        return this.permicoeses;
    }
    
    public void setPermicoeses(Set permicoeses) {
        this.permicoeses = permicoeses;
    }
    public Set getPermissoeses() {
        return this.permissoeses;
    }
    
    public void setPermissoeses(Set permissoeses) {
        this.permissoeses = permissoeses;
    }
    public Set getAuditorias() {
        return this.auditorias;
    }
    
    public void setAuditorias(Set auditorias) {
        this.auditorias = auditorias;
    }




}


