/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.chamados.view.pessoa;

import br.com.chamados.view.pessoa.*;
import br.com.chamados.config.LogChamados;
import br.com.chamados.dao.CidadeDao;
import br.com.chamados.dao.EmpresaDao;
import br.com.chamados.dao.PessoaDao;
import br.com.chamados.dao.EstadoDao;
import br.com.chamados.genericos.AcoesPainel;
import br.com.chamados.genericos.Campos;
import br.com.chamados.genericos.Cookies;
import br.com.chamados.model.Cidade;
import br.com.chamados.model.Pessoa;
import br.com.chamados.model.Permissoes;
import br.com.chamados.utils.CampoInteiro;
import br.com.chamados.utils.CombosDAO;
import br.com.chamados.genericos.campos.DesabilitaCampos;
import br.com.chamados.genericos.campos.LimparCampos;
import br.com.chamados.utils.CampoCPF;
import br.com.chamados.utils.ItemCombo;
import br.com.chamados.view.JpDefault;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import javax.swing.JButton;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;
import org.apache.log4j.Logger;
import org.hibernate.HibernateException;

/**
 *
 * @author Jonas C. Rosa
 */
public class JFPessoa extends JInternalFrame implements AcoesPainel {

    /**
     * Creates new form JFPessoa
     */
    private Logger logger = Logger.getLogger(LogChamados.class);
    private IfPessoa iFPessoa;
    private Pessoa pessoa;

    public JFPessoa() {
        initComponents();
        initMyComponents();
        this.setTitle("Pessoa");
    }

    private void initMyComponents() {
        JpDefault jpDefault = new JpDefault();
        jpDefault.setBounds(10, 10, 450, 180);
        this.add(jpDefault);
        jpDefault.setAcoesCadastro(this);
        EstadoDao.preencherCombo(jcEstado);
//        vaPara("0");
        try {
            new MaskFormatter("##/##/####").install(jftDataNasc);
        } catch (ParseException ex) {
            Logger.getLogger(JFPessoa.class.getName());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JdEmpresas = new javax.swing.JDesktopPane();
        jtEmpresa = new javax.swing.JTabbedPane();
        jpPessoa = new javax.swing.JPanel();
        jtNome = new javax.swing.JTextField();
        jlNomeEmpresa = new javax.swing.JLabel();
        jlEmailEmpresa = new javax.swing.JLabel();
        jtEmail = new javax.swing.JTextField();
        jlTelefoneEmpresa = new javax.swing.JLabel();
        jtTelefone = new javax.swing.JTextField();
        jlCgc = new javax.swing.JLabel();
        jtIdade = new CampoInteiro();
        jlCidadeEmpresa = new javax.swing.JLabel();
        jcEstado = new javax.swing.JComboBox();
        jlBairroEmpresa = new javax.swing.JLabel();
        jcCidade = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jtCampo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtRg = new CampoInteiro();
        jLabel4 = new javax.swing.JLabel();
        jtCpf = new CampoCPF();
        jLabel5 = new javax.swing.JLabel();
        jftDataNasc = new javax.swing.JFormattedTextField();
        jbCancelar = new javax.swing.JButton();
        jbSalvar = new javax.swing.JButton();

        jtEmpresa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtEmpresaMouseClicked(evt);
            }
        });

        jtNome.setEnabled(false);
        jtNome.setName("Nome"); // NOI18N

        jlNomeEmpresa.setText("Nome");

        jlEmailEmpresa.setText("Email");

        jtEmail.setEnabled(false);
        jtEmail.setName("Email"); // NOI18N

        jlTelefoneEmpresa.setText("Telefone");

        jtTelefone.setEnabled(false);
        jtTelefone.setName("Telefone"); // NOI18N

        jlCgc.setText("Idade");

        jtIdade.setEnabled(false);
        jtIdade.setName("CGC"); // NOI18N

        jlCidadeEmpresa.setText("Estado");

        jcEstado.setEnabled(false);
        jcEstado.setName("Estado"); // NOI18N
        jcEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcEstadoActionPerformed(evt);
            }
        });

        jlBairroEmpresa.setText("Cidade");

        jcCidade.setEnabled(false);
        jcCidade.setName("Cidade"); // NOI18N

        jLabel1.setText("Id");

        jtCampo.setEditable(false);

        jLabel3.setText("CPF");

        jLabel4.setText("RG");

        jLabel5.setText("Data de nascimento");

        javax.swing.GroupLayout jpPessoaLayout = new javax.swing.GroupLayout(jpPessoa);
        jpPessoa.setLayout(jpPessoaLayout);
        jpPessoaLayout.setHorizontalGroup(
            jpPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPessoaLayout.createSequentialGroup()
                .addGroup(jpPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpPessoaLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jpPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpPessoaLayout.createSequentialGroup()
                                .addComponent(jlNomeEmpresa)
                                .addGap(18, 18, 18)
                                .addComponent(jtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpPessoaLayout.createSequentialGroup()
                                .addGroup(jpPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jlCgc))
                                .addGap(18, 18, 18)
                                .addGroup(jpPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jpPessoaLayout.createSequentialGroup()
                        .addGroup(jpPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpPessoaLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(jpPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jlEmailEmpresa)
                                    .addComponent(jlTelefoneEmpresa)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpPessoaLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jlCidadeEmpresa)))
                        .addGap(18, 18, 18)
                        .addGroup(jpPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jpPessoaLayout.createSequentialGroup()
                                .addGroup(jpPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addGroup(jpPessoaLayout.createSequentialGroup()
                                        .addComponent(jcEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(25, 25, 25)
                                        .addComponent(jlBairroEmpresa))
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(jpPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtRg)
                                    .addComponent(jcCidade, 0, 175, Short.MAX_VALUE)
                                    .addComponent(jftDataNasc)))))
                    .addGroup(jpPessoaLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jtCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpPessoaLayout.setVerticalGroup(
            jpPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpPessoaLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jpPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNomeEmpresa)
                    .addComponent(jtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlCgc)
                    .addComponent(jLabel5)
                    .addComponent(jftDataNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jpPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jcCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jlBairroEmpresa))
                    .addGroup(jpPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jcEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jlCidadeEmpresa)))
                .addGap(18, 18, 18)
                .addGroup(jpPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlEmailEmpresa)
                    .addComponent(jtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpPessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlTelefoneEmpresa)
                    .addComponent(jtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(101, Short.MAX_VALUE))
        );

        jtNome.getAccessibleContext().setAccessibleName("Nome");
        jtEmail.getAccessibleContext().setAccessibleName("E-mail");
        jtTelefone.getAccessibleContext().setAccessibleName("Telefone");
        jtTelefone.getAccessibleContext().setAccessibleDescription("");
        jtIdade.getAccessibleContext().setAccessibleName("");
        jcEstado.getAccessibleContext().setAccessibleName("Estado");
        jcCidade.getAccessibleContext().setAccessibleName("Cidade");

        jtEmpresa.addTab("Pessoa", jpPessoa);

        jbCancelar.setText("Cancelar");
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        jbSalvar.setText("Salvar");
        jbSalvar.setEnabled(false);
        jbSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JdEmpresasLayout = new javax.swing.GroupLayout(JdEmpresas);
        JdEmpresas.setLayout(JdEmpresasLayout);
        JdEmpresasLayout.setHorizontalGroup(
            JdEmpresasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JdEmpresasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JdEmpresasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtEmpresa)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JdEmpresasLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbCancelar)
                        .addGap(18, 18, 18)
                        .addComponent(jbSalvar)))
                .addGap(13, 13, 13))
        );
        JdEmpresasLayout.setVerticalGroup(
            JdEmpresasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JdEmpresasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, 432, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JdEmpresasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCancelar)
                    .addComponent(jbSalvar))
                .addGap(21, 21, 21))
        );
        JdEmpresas.setLayer(jtEmpresa, javax.swing.JLayeredPane.DEFAULT_LAYER);
        JdEmpresas.setLayer(jbCancelar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        JdEmpresas.setLayer(jbSalvar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JdEmpresas)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 70, Short.MAX_VALUE)
                .addComponent(JdEmpresas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalvarActionPerformed
        try {
            Cidade cidade = new Cidade();
            cidade.setId(((ItemCombo) jcCidade.getSelectedItem()).getCodigo());
            Pessoa pessoa = new Pessoa();
            if (!jtCampo.getText().equals(PessoaDao.proximoId())) {
                pessoa.setId(Integer.parseInt(jtCampo.getText()));
            }
            pessoa.setNome(jtNome.getText());
            pessoa.setIdade(Integer.parseInt(jtIdade.getText()));
            pessoa.setCpf(jtCpf.getText());
            pessoa.setRg(jtRg.getText());
            pessoa.setEmail(jtEmail.getText());
            pessoa.setTelefone(jtTelefone.getText());
            String data = jftDataNasc.getText();
            SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
            try {
                Date d = format.parse(data);
                pessoa.setDataNascimento(d);
            } catch (ParseException ex) {
                java.util.logging.Logger.getLogger(JFPessoa.class.getName()).log(Level.SEVERE, null, ex);
            }
            pessoa.setCidade(cidade);
            if (Campos.validar(jpPessoa)) {
                PessoaDao.save(pessoa);
                DesabilitaCampos.run(jpPessoa);
                LimparCampos.run(jpPessoa);
            }
            jbSalvar.setEnabled(false);
        } catch (HibernateException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Erro ao salvar");
        }
    }//GEN-LAST:event_jbSalvarActionPerformed

    private void jcEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcEstadoActionPerformed
        jcCidade.removeAllItems();
        if (jcEstado.getSelectedIndex() > 0) {
            new CombosDAO().popularCidade(jcCidade,
                    jcEstado.getSelectedIndex());
            jcCidade.setEnabled(true);
        }
    }//GEN-LAST:event_jcEstadoActionPerformed

    private void jtEmpresaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtEmpresaMouseClicked
//        PessoaDao.popularTabela(jTable1, null);

    }//GEN-LAST:event_jtEmpresaMouseClicked

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        hide();
    }//GEN-LAST:event_jbCancelarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane JdEmpresas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbSalvar;
    private javax.swing.JComboBox jcCidade;
    private javax.swing.JComboBox jcEstado;
    private javax.swing.JFormattedTextField jftDataNasc;
    private javax.swing.JLabel jlBairroEmpresa;
    private javax.swing.JLabel jlCgc;
    private javax.swing.JLabel jlCidadeEmpresa;
    private javax.swing.JLabel jlEmailEmpresa;
    private javax.swing.JLabel jlNomeEmpresa;
    private javax.swing.JLabel jlTelefoneEmpresa;
    private javax.swing.JPanel jpPessoa;
    private javax.swing.JTextField jtCampo;
    private javax.swing.JTextField jtCpf;
    private javax.swing.JTextField jtEmail;
    private javax.swing.JTabbedPane jtEmpresa;
    private javax.swing.JTextField jtIdade;
    private javax.swing.JTextField jtNome;
    private javax.swing.JTextField jtRg;
    private javax.swing.JTextField jtTelefone;
    // End of variables declaration//GEN-END:variables

    public void vaPara(String vaPara) {
        if (vaPara.equals("")) {
            vaPara = JOptionPane.showInputDialog("Vá para");
            if (vaPara == null || vaPara.equals("")) {
                vaPara = "0";
            }
        }
        pessoa = PessoaDao.vaPara(vaPara);
        if (pessoa != null) {

            jtCampo.setText(String.valueOf(pessoa.getId()));
            jtNome.setText(pessoa.getNome());
            jtIdade.setText(String.valueOf(pessoa.getIdade()));
            jtTelefone.setText(pessoa.getTelefone());
            jtCpf.setText(pessoa.getCpf());
            jtRg.setText(pessoa.getRg());
            jtEmail.setText(pessoa.getEmail());

            SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
            Date y = pessoa.getDataNascimento();
            jftDataNasc.setText(format.format(y));

            ItemCombo uf = new ItemCombo();
            Cidade cidade = CidadeDao.getEstadoId(pessoa.getCidade().getId());
            uf.setCodigo(cidade.getEstado().getId());
            new CombosDAO().definirItemCombo(jcEstado, uf);

            jcCidade.setEnabled(true);
            ItemCombo c = new ItemCombo();
            c.setCodigo(cidade.getId());
            new CombosDAO().definirItemCombo(jcCidade, c);

        } else {
            Campos.limpar(jpPessoa);
            Campos.desabilitar(jpPessoa);
        }
    }

    @Override
    public void pesquisar() {
        if (iFPessoa == null) {
            iFPessoa = new IfPessoa(this);
        }
        PessoaDao.popularTabela(iFPessoa.getTabela(), null);
        iFPessoa.setModal(true);
        iFPessoa.setVisible(true);
        jbSalvar.setEnabled(true);
    }

    @Override
    public void inserir() {
        Campos.habilitar(jpPessoa);
        Campos.limpar(jpPessoa);
        jtCampo.setText(PessoaDao.proximoId());
        jtCampo.setEditable(false);
        jbSalvar.setEnabled(true);
    }

    @Override
    public void alterar() {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void deletar() {
        int opcao = JOptionPane.showConfirmDialog(null, "Confirma exclução do registro?", "Deletar Registro", JOptionPane.YES_NO_OPTION);
        if (opcao == 0) {
            PessoaDao.deletar(pessoa);
            Campos.limpar(jpPessoa);
            Campos.desabilitar(jpPessoa);
        }
    }

    @Override
    public void checkEnabled(JButton jbInserir, JButton jbAlterar, JButton jbDeletar) {
        for (Permissoes permissoes : Cookies.listaPermissoes) {
            if (permissoes.getTela().getDescricao().equalsIgnoreCase(this.getClass().getSimpleName())) {
                jbInserir.setEnabled(permissoes.getInserir());
                jbAlterar.setEnabled(permissoes.getAlterar());
                jbDeletar.setEnabled(permissoes.getDeletar());
            }
        }
    }

    public void setFormPessoa(Pessoa pessoa) {
        this.pessoa = pessoa;

        jtCampo.setText(String.valueOf(pessoa.getId()));
        jtNome.setText(pessoa.getNome());
        jtIdade.setText(String.valueOf(pessoa.getIdade()));
        jtTelefone.setText(pessoa.getTelefone());
        jtCpf.setText(pessoa.getCpf());
        jtRg.setText(pessoa.getRg());
        jtEmail.setText(pessoa.getEmail());

        SimpleDateFormat format = new SimpleDateFormat("dd-MM-yyyy");
        Date y = pessoa.getDataNascimento();
        jftDataNasc.setText(format.format(y));

        ItemCombo uf = new ItemCombo();
        Cidade cidade = CidadeDao.getEstadoId(pessoa.getCidade().getId());
        uf.setCodigo(cidade.getEstado().getId());
        new CombosDAO().definirItemCombo(jcEstado, uf);

        jcCidade.setEnabled(true);
        ItemCombo c = new ItemCombo();
        c.setCodigo(cidade.getId());
        new CombosDAO().definirItemCombo(jcCidade, c);

        Campos.habilitar(jpPessoa);
        jbSalvar.setEnabled(true);
    }

    public Pessoa obterFromPessoa() {
        return this.pessoa;
    }

    @Override
    public void salvar() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void cancelar() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void fechar() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
