/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.chamados.view.chamado;

import br.com.chamados.dao.InteracaoDao;
import br.com.chamados.genericos.Cookies;
import br.com.chamados.model.Chamado;
import br.com.chamados.model.Interacao;
import br.com.chamados.view.JfMenu;
import java.awt.Frame;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author jonascr86
 */
public class JdAdicionarComentario extends javax.swing.JDialog {

    /**
     * Creates new form JdAdicionarComentario
     */
    private Chamado chamadoComentario;
    private static JdMostrarInteracao jdMostrarInteracao;
    private static JfMenu jfMenu;
    
    
    public JdAdicionarComentario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public JdAdicionarComentario(java.awt.Frame parent, boolean modal, Chamado chamado) {
        super(parent, modal);
        initComponents();
        chamadoComentario = chamado;
        popularTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpAdicionarComentario = new javax.swing.JPanel();
        jspAdicionarComentario = new javax.swing.JScrollPane();
        jtAdicionarComentario = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtComentario = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jtAdicionarComentario.setColumns(20);
        jtAdicionarComentario.setRows(5);
        jspAdicionarComentario.setViewportView(jtAdicionarComentario);

        jButton1.setText("Salvar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jtComentario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Data", "Comentário", "Autor"
            }
        ));
        jtComentario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtComentarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtComentario);

        javax.swing.GroupLayout jpAdicionarComentarioLayout = new javax.swing.GroupLayout(jpAdicionarComentario);
        jpAdicionarComentario.setLayout(jpAdicionarComentarioLayout);
        jpAdicionarComentarioLayout.setHorizontalGroup(
            jpAdicionarComentarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAdicionarComentarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpAdicionarComentarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpAdicionarComentarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpAdicionarComentarioLayout.createSequentialGroup()
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton2))
                        .addComponent(jspAdicionarComentario, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 885, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jpAdicionarComentarioLayout.setVerticalGroup(
            jpAdicionarComentarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAdicionarComentarioLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jspAdicionarComentario, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jpAdicionarComentarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpAdicionarComentario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpAdicionarComentario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(chamadoComentario != null){
            salvarComentario();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        chamadoComentario = null;
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jtComentarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtComentarioMouseClicked
        if (evt.getClickCount() == 2) {
            selecionarInteracao();
        }
    }//GEN-LAST:event_jtComentarioMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JdAdicionarComentario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JdAdicionarComentario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JdAdicionarComentario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JdAdicionarComentario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JdAdicionarComentario dialog = new JdAdicionarComentario(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    
    private void salvarComentario(){
        String descricao = "";
        String quem = Cookies.usuario.getFuncionario().getPessoa().getNome();
        SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/YYYY");
        Date date = new Date();
        String quando = formatter.format(date);
        
        descricao += "Chamado " + chamadoComentario.getId() + " " + chamadoComentario.getTitulo() + " \n";
        descricao += "Comentário adicionado por " + quem + " em " + quando + " \n";
        descricao += jtAdicionarComentario.getText() + "\n\n\n";
        
        Interacao interacao = new Interacao();
        interacao.setFuncionario(Cookies.usuario.getFuncionario());
        interacao.setChamado(chamadoComentario);
        interacao.setData(date);
        interacao.setDescricao(descricao);
        
        InteracaoDao.salvar(interacao);
        popularTabela();
        
    }
    
    private void popularTabela(){
        Interacao interacaoTabela = new Interacao();
        interacaoTabela.setChamado(chamadoComentario);
        InteracaoDao.popularTabela(jtComentario, interacaoTabela);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpAdicionarComentario;
    private javax.swing.JScrollPane jspAdicionarComentario;
    private javax.swing.JTextArea jtAdicionarComentario;
    private javax.swing.JTable jtComentario;
    // End of variables declaration//GEN-END:variables

    private void selecionarInteracao() {
        int interacaoId = (int) jtComentario.getValueAt(jtComentario.getSelectedRow(), 0);
        Interacao bInteracao = new Interacao();
        bInteracao.setId(interacaoId);
        Interacao interacao = InteracaoDao.obterInteracao(bInteracao).get(0);
        mostrarInteracao(interacao);
    }

    private void mostrarInteracao(Interacao interacao) {
        jdMostrarInteracao = new JdMostrarInteracao(jfMenu, true, interacao);
        jdMostrarInteracao.setVisible(true);
        jdMostrarInteracao.toFront();
    }
}